[GOBBLIN-1359] Fix the error that IOException thrown by writer be swallowed by Reactivex
apache/incubator-gobblin pull request #3200
Opened 2021-01-13 19:17 UTC by ZihanLi58

…llowed by Reactivex

Dear Gobblin maintainers,

Please accept this PR. I understand that it will not be reviewed until I have checked off all the steps below!

### JIRA
- [ ] My PR addresses the following [Gobblin JIRA](https://issues.apache.org/jira/browse/GOBBLIN/) issues and references them in the PR title. For example, "[GOBBLIN-XXX] My Gobblin PR"
    - https://issues.apache.org/jira/browse/GOBBLIN-1359

### Description
- [ ] Here are some details about my PR, including screenshots (if applicable):
Fix the bug in Reactivex code which swallows the exception and leaves the task hanging

### Tests
- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:
Create dummy IOException in writer and make sure it can cause the task failure

### Commits
- [ ] My commits all reference JIRA issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

2021-01-13 19:18 UTC, ZihanLi58 commented
@sv2000 Can you help take a look at this minor change for the Reactivex bug

2021-01-13 20:00 UTC, sv2000 commented on gobblin-runtime/src/main/java/org/apache/gobblin/runtime/fork/Fork.java
> +          throw(new RuntimeException(e));
Any reason why it is being wrapped into RuntimeException? Can we just rethrow e as is?

2021-01-13 20:01 UTC, sv2000 requested changes
A minor comment.

2021-01-14 04:12 UTC, sv2000 commented on gobblin-runtime/src/main/java/org/apache/gobblin/runtime/fork/Fork.java
> +          throw((Exception) e);
Sorry - I did not realize earlier that e is a throwable, in which case I now understand why you had to wrap it into a RuntimeException. I think that would be better than casting to an Exception.

2021-01-14 17:23 UTC, sv2000 approved these changes
+1. LGTM.

2021-01-19 18:39 UTC, closed without merging